pyproject.toml, src/tdastro/sources/spline_model.py, tests/tdastro/sources/test_spline_source.py
Add a spline-based `PhysicalModel` based on the `TimeSeriesModel` from sncosmo
=> Add a spline-based model

src/tdastro/base_models.py, src/tdastro/sources/spline_model.py, src/tdastro/sources/static_source.py, src/tdastro/sources/step_source.py, tests/tdastro/sources/test_static_source.py, tests/tdastro/sources/test_step_source.py
Currently TDAstro requires the creation of a new `PhysicalModel`s anytime we resample the parameters. This might be expensive. This PR adds a slightly more flexible model where the `PhysicalModel` can pull attributes samples from functions. It is still a bit awkward because the function parameters need different names.
A next step will be to extend this to take in a DAG of sampling effects and do the sampling based on that DAG.
=> Create better resampling

src/tdastro/base_models.py, src/tdastro/sources/spline_model.py, src/tdastro/sources/static_source.py, src/tdastro/sources/step_source.py, tests/tdastro/sources/test_spline_source.py, tests/tdastro/sources/test_static_source.py, tests/tdastro/sources/test_step_source.py, tests/tdastro/test_base_models.py
Create a more flexible sampling model that is closer to the DAG. Instead of being able to sample parameters from three sources (a constant, a function, or a host's attribute) allow the following sources:
- A constant value
- A function
- The attribute of any other model (including a host, statistical distribution, or something else)
- A function from any other model (including a host, statistical distribution, or something else)
This removes the use of a pre-specified `host` attribute. It also creates a generalized `ParameterizedModel` that we can use for populations or even effects. The various `ParameterizedModel`s can form a DAG.
=> Allow DAG construction from models

src/tdastro/base_models.py, src/tdastro/effects/white_noise.py, src/tdastro/sources/spline_model.py, src/tdastro/sources/static_source.py, src/tdastro/sources/step_source.py, tests/tdastro/sources/test_step_source.py
Closes #15 
Most of the `__init__()` level comments were duplicates anyway.
=> Move __init__ comments into class comments

src/tdastro/base_models.py, src/tdastro/effects/white_noise.py, tests/tdastro/effects/test_white_noise.py, tests/tdastro/test_base_models.py
Two changes to improve how the parameter sampling works:
- Parameters are sampled in the order in which they are added (by changing the dictionary to a list). This allows for dependencies among the parameters.
- An `EffectModel` can have and resample functional parameters.
=> Expand the DAG resampling

src/tdastro/base_models.py
Change the setters list to a dictionary to make the look ups faster. As Kostya noted in #27, dictionaries preserve the order in which the items were inserted.
=> Change setters list to dict

src/tdastro/base_models.py, src/tdastro/effects/effect_model.py, src/tdastro/effects/white_noise.py, src/tdastro/populations/fixed_population.py, src/tdastro/populations/population_model.py, src/tdastro/sources/galaxy_models.py, src/tdastro/sources/periodic_source.py, src/tdastro/sources/physical_model.py, src/tdastro/sources/sncomso_models.py, src/tdastro/sources/spline_model.py, src/tdastro/sources/static_source.py, tests/tdastro/sources/test_physical_models.py, tests/tdastro/test_base_models.py
Break about `base_models.py` because it is becoming too large and complex. Moves the second level models (`PhysicalModel`, `EffectModel`, and `PopulationModel`) into the corresponding subdirectories. Update the comments to clarify what `base_models.py` contains.
Also renames `ParameterizedModel` to `ParameterizedNode` in preparation for more substantial DAG PR.
=> Reorganize the base classes

src/tdastro/base_models.py, tests/tdastro/test_base_models.py
We want to __str__() result of a `FunctionNode` to include the function it is calling so we can use multiple `FunctionNode`s in a single graph.
=> Extend the __str__() method of FunctionNode

pyproject.toml, src/tdastro/base_models.py, src/tdastro/util_nodes/jax_random.py, src/tdastro/util_nodes/np_random.py, tests/tdastro/util_nodes/test_jax_random.py, tests/tdastro/util_nodes/test_np_random.py
Add random number generator functions from both jax and numpy. These subclass the `FunctionNode` so they can be included directly as nodes in the execution graph. Both node types handle the seeding and maintaining of their respective random number generators.
=> Add wrappers to random number generators

src/tdastro/base_models.py, tests/tdastro/test_base_models.py
Store a list of direct dependencies, which are parent nodes in the execution graph. This will allow us to run faster graph traversals that do not require always iterating over every attribute. Regenerate the list of direct dependencies any time an attribute is changes (should be fast since it is not recursive).
Remove the unused `get_dependencies()` function which did the recursive search.
=> Store a list of direct dependencies

src/tdastro/base_models.py, src/tdastro/effects/white_noise.py, src/tdastro/sources/galaxy_models.py, src/tdastro/sources/physical_model.py, src/tdastro/util_nodes/jax_random.py, src/tdastro/util_nodes/np_random.py, tests/tdastro/effects/test_white_noise.py, tests/tdastro/sources/test_galaxy_models.py, tests/tdastro/test_base_models.py, tests/tdastro/util_nodes/test_jax_random.py, tests/tdastro/util_nodes/test_np_random.py
Changes how the set is set in the `ParameterizedNode`. Seeds are still determined by a combination of a `graph_base_seed` (which is initially set to completely random) and the node's string. The node's string has been expanded to include its position in the graph (if known).
**Why?** The previous approach of just using the node’s identifier (and **not** the position in the graph) was easy to make a mistake when using two of the same nodes in the graph. This makes it more difficult for a user to make such a mistake.
Other changes:
- `sample_iteration` has been replaced by using a depth-first search and passing along the seen nodes. This will allow us to sample a subset of the graph while keeping the rest fixed. This means we can also get rid of `check_resample()`.
- `_node_id` has been …
=> Redo the random seeding

src/tdastro/base_models.py, tests/tdastro/test_base_models.py
Make the ordering of `direct_dependencies` stable by changing it from a set to a dict. Test this by forcing an update of the graph numbering when we call `get_all_parameter_values()` and augmenting the test to check the node numbers (their names start with "number: ...").
=> Make the ordering of direct_dependencies stable

src/tdastro/base_models.py, tests/tdastro/test_base_models.py
Several expansions to the TDAstro evaluation graph
1) If a raw function or method is passed as a value, the code will automatically wrap it in a `FunctionNode`.
2) We allow a `FunctionNode` to compute multiple output values.
3) We clear the parameter values when we update the graph information (this will increase (but not completely remove) the likelihood of failing if there is a loop in the execution graph)
=> Function expansion

src/tdastro/sources/sncomso_models.py, tests/tdastro/sources/test_sncosmo_models.py
Fix a problem where the parameter setting to a `SncosmoWrapperModel` were not be propagated to the underlying model. We need to call `self.source.set()` with the correct parameters each time the wrapper model itself is updated. This PR makes that automatic.
=> Fix parameter setting for sncosmo models

src/tdastro/astro_utils/cosmology.py, src/tdastro/base_models.py, src/tdastro/effects/redshift.py, src/tdastro/effects/white_noise.py, src/tdastro/populations/population_model.py, src/tdastro/sources/galaxy_models.py, src/tdastro/sources/periodic_source.py, src/tdastro/sources/periodic_variable_star.py, src/tdastro/sources/physical_model.py, src/tdastro/sources/sncomso_models.py, src/tdastro/sources/spline_model.py, src/tdastro/sources/static_source.py, src/tdastro/sources/step_source.py, src/tdastro/util_nodes/jax_random.py, tests/tdastro/effects/test_white_noise.py, tests/tdastro/populations/test_fixed_population.py, tests/tdastro/sources/test_galaxy_models.py, tests/tdastro/sources/test_physical_models.py, tests/tdastro/sources/test_sncosmo_models.py, tests/tdastro/sources/test_static_source.py, tests/tdastro/sources/test_step_source.py, tests/tdastro/test_base_models.py
Change how both node's parameters are stored in the `ParameterizedNode` objects and how they are access. Instead of storing each parameter as an object attribute (and using `getattr()` and `setattr()`), we now store the parameter values in a dictionary called `parameters`.
**Why?** Being able to access the parameter's directly could lead to confusion during chaining and accidental setting of attributes. For example doing something like `source.ra = 10.0` could cause a problem is the source's RA is supposed to be set from the host. Similarly saying `x1=HostmassX1Func(host.hostmass)` would set `x1` as the current value of the hostmass instead of linking to the object's parameter.
Practically this means that now parameters are referenced via the `parameter` dictionary within a node
**OLD**: …
=> Change how we access another node's attributes

tests/tdastro/sources/test_static_source.py, tests/tdastro/sources/test_step_source.py, tests/tdastro/test_base_models.py
Replace uses of `get_parameter()` in testing with the `[]` access.
=> Remove unused get_parameter() function

src/tdastro/base_models.py, src/tdastro/util_nodes/jax_random.py, src/tdastro/util_nodes/np_random.py, tests/tdastro/effects/test_redshift.py, tests/tdastro/sources/test_step_source.py, tests/tdastro/test_base_models.py, tests/tdastro/util_nodes/test_jax_random.py, tests/tdastro/util_nodes/test_np_random.py
This is a prefactoring PR for some JAX related changes. The goal is to modularize how the parameters are set. The changes should not impact current users and (mostly) be behind the scenes.
What is changing:
1) `ParameterSource` classes is extended to track named information like `source_type` or `fixed`. Previously this was tracked in an array entry and accessed with a magic index number. This should make it easier to see what the code is doing and add new attributes to the setters.
2) `ParameterizedNode` attributes can no longer be set by arbitrary methods of other `ParameterizedNode`s. This was preventing us from easily checking that the evaluation graph was a DAG.
3) The results of a `FunctionNode` are now accessed through their attributes. This prevents problems where the same …
=> Update the core logic for updating parameters

src/tdastro/base_models.py, tests/tdastro/sources/test_spline_source.py, tests/tdastro/sources/test_static_source.py, tests/tdastro/test_base_models.py
Make a few changes to clean up the logic behind node strings:
1) Rename `node_indentifier` to `node_label` to make it clearer it is a human generated label.
2) Cache the node string (`node_string`) and only regenerate it if something has changed. We do this because the node string is increasingly being used to access information (such as variable names).
3) Don't output the module + class if a user provided label is present.
=> Node name cleanup

src/tdastro/base_models.py, tests/tdastro/test_base_models.py
Cache the parameter's full name in the setter_info. This will allow us to efficiently look it up from a dictionary in other PRs such as #60.
This PR also cleans up how the overloading of the name works with `FunctionNode` so that it caches the node's name correctly (which I broke in #58).
=> Cache the parameter's full name in the setter_info

src/tdastro/base_models.py, src/tdastro/sources/physical_model.py, src/tdastro/sources/sncomso_models.py, tests/tdastro/test_base_models.py
Nodes can generate PyTrees with new `build_pytree()` function which will generate a pytree dictionary for the current tree of nodes. The same dictionary can be passed through the sampling functions as `given_args` to override any of the internal settings.
=> JAX Compatibility Step 1: Allow Nodes to generate and use PyTrees

src/tdastro/base_models.py, src/tdastro/effects/effect_model.py, src/tdastro/effects/redshift.py, src/tdastro/effects/white_noise.py, src/tdastro/populations/population_model.py, src/tdastro/sources/galaxy_models.py, src/tdastro/sources/periodic_source.py, src/tdastro/sources/periodic_variable_star.py, src/tdastro/sources/physical_model.py, src/tdastro/sources/sncomso_models.py, src/tdastro/sources/spline_model.py, src/tdastro/sources/static_source.py, src/tdastro/sources/step_source.py, src/tdastro/util_nodes/jax_random.py, src/tdastro/util_nodes/np_random.py, tests/tdastro/astro_utils/test_cosmology.py, tests/tdastro/astro_utils/test_passbands.py, tests/tdastro/effects/test_white_noise.py, tests/tdastro/populations/test_fixed_population.py, tests/tdastro/sources/test_galaxy_models.py, tests/tdastro/sources/test_periodic_source.py, tests/tdastro/sources/test_physical_models.py, tests/tdastro/sources/test_sncosmo_models.py, tests/tdastro/sources/test_spline_source.py, tests/tdastro/sources/test_static_source.py, tests/tdastro/sources/test_step_source.py, tests/tdastro/test_base_models.py, tests/tdastro/util_nodes/test_jax_random.py, tests/tdastro/util_nodes/test_np_random.py
Move the internal state of the model's parameters to an external dictionary `graph_state`. For details about the motivation and implementation, see the design document [here](https://docs.google.com/document/d/12UndUkKDTGjW_S3kVPLmnEEn9l-YeZ_CunjYduBygDI/edit).
=> Make TDAstro's sampling stateless

src/tdastro/base_models.py, src/tdastro/sources/physical_model.py, src/tdastro/sources/sncomso_models.py, src/tdastro/util_nodes/jax_random.py, src/tdastro/util_nodes/np_random.py, tests/tdastro/test_base_models.py, tests/tdastro/util_nodes/test_jax_random.py, tests/tdastro/util_nodes/test_np_random.py
Remove all the random seed information from the `ParameterizedNode` and instead only maintain it in the numpy and JAX random node classes. This removes a lot of complexity in the base class.
JAX random number generation nodes are stateless and requires the user pass in the current keys each time.
Numpy random number generation nodes can be stateful (with their own stored random number generation) or stateless (with a passed in dictionary of the random number generators).
This PR also adds all the plumbing for passing around the random number generators/keys/state. This adds some complexity to the function signatures, but means that the nodes behave statelessly.
=> Make the JAX random number generation stateless

src/tdastro/sources/galaxy_models.py, src/tdastro/sources/periodic_source.py, src/tdastro/sources/physical_model.py, src/tdastro/sources/sncomso_models.py, src/tdastro/sources/spline_model.py, src/tdastro/sources/static_source.py, src/tdastro/sources/step_source.py, tests/tdastro/sources/test_sncosmo_models.py
Add a t0 parameter to sncosmo models. Like all parameter this can be sampled if a function is passed in.
Also expands the comments to indicate which times are in rest frame vs observer frame.
=> Add a t0 parameter to sncosmo models

src/tdastro/base_models.py, src/tdastro/sources/physical_model.py, src/tdastro/util_nodes/jax_random.py, src/tdastro/util_nodes/np_random.py, tests/tdastro/sources/test_physical_models.py
Refactor some of `FunctionNode.compute()` by adding two helper functions to prepare the arguments and save the data.  Use those helpers to cleanup some of the logic in the numpy and JAX random generators.
Also adds a helper function for setting random seeds for a `PhysicalModel`.
=> Pre-factoring and helper functions

src/tdastro/graph_state.py, tests/tdastro/test_graph_state.py
This PR adds some helper functions that will be used in future functionality:
1) Set values in a `GraphState` from a dictionary or another `GraphState`
2) Allow the `GraphState` to fix some values (needed for JAX gradients).
=> Add a helper functions for GraphState

src/tdastro/base_models.py, src/tdastro/graph_state.py, src/tdastro/sources/physical_model.py, src/tdastro/sources/sncomso_models.py, src/tdastro/util_nodes/jax_random.py, src/tdastro/util_nodes/np_random.py, src/tdastro/util_nodes/scipy_random.py, tests/tdastro/sources/test_sncosmo_models.py, tests/tdastro/sources/test_spline_source.py, tests/tdastro/sources/test_static_source.py, tests/tdastro/test_base_models.py, tests/tdastro/test_graph_state.py
The goal of this PR is to cleanup and simplify the internal logic for sampling so it is easier to understand and debug. To this end, it:
- Adds a `__str__()` function to `GraphState` that produces a human readable debugging string. 
- Replaces the nodes' hash value with the nodes' (readable) string in `GraphState`. This will add slight overhead in indexing (to hash the string), but greatly increase testability and debug-ability.
- Switch the PyTree to use the same dictionary structure as `GraphState` (a double index of [node_name][var_name]). This allows:
- Removing the now unused `full_name` attribute from `ParameterSource`
- Removing a lot of specialized logic that was needed to handle `given_args`. Instead the `given_args` are merged directly into the current `GraphState` as fixed …
=> Cleanup and simplify internal logic

.gitignore, docs/notebooks/test_snia.ipynb, pyproject.toml, src/tdastro/astro_utils/passbands.py, tests/tdastro/sources/test_snia.py
- Fixed passband caching system to use URL in filename, to avoid unwittingly using wrong locally cached files.
- Added passband file cache to .gitignore so `git status` doesn't report untracked files.
- Changed path in example ipynb to be relative to tdastro module path rather than hardcoded
- Fixed passbands.py to accept the LSST files from LSST github,
- passbands.py now accepts a unit parameter for angstrom vs nm so LSST github files can be configured to work, as well as legacy files from svo2.cab.inta-csic.es
- Fixed wavelength overlap condition and fluxes_to_bandflux() calculation so that longer passband tables from github work.
=> Fixes for various issues trying to set up first time

src/tdastro/astro_utils/opsim.py, tests/tdastro/astro_utils/test_opsim.py
Make `OpSim` easier to use for testing:
- Provide a more meaningful error if zero points are not provided.
- Add the helper method `has_columns()` that wraps the column name map.
- Add a function to add columns with column name map support.
- Add the function `opsim_add_random_data()` to create a new column filled with random data (for testing).
=> Increate the flexibility of the OpSim Table.

tests/tdastro/util_nodes/test_np_random.py
Closes #101 
Set a seed for the tests, so they don't randomly fail.
=> Fix stochastic bug

src/tdastro/astro_utils/passbands.py, src/tdastro/base_models.py, src/tdastro/effects/redshift.py, src/tdastro/effects/white_noise.py, src/tdastro/sources/galaxy_models.py, src/tdastro/sources/periodic_source.py, src/tdastro/sources/periodic_variable_star.py, src/tdastro/sources/physical_model.py, src/tdastro/sources/snia_host.py, src/tdastro/sources/static_source.py, src/tdastro/sources/step_source.py, tests/tdastro/sources/test_physical_models.py, tests/tdastro/sources/test_static_source.py, tests/tdastro/test_base_models.py
Allow us to set whether we compute a gradient for a given parameter in the PyTree. The default is `True` for all constant and `False` for everything else. But we can now do overrides.
Also removes the `required` and `fixed` fields from the setter info as these are not needed. The `fixed` setting has been replaced by `allow_gradient`. The `required` field is not needed because the program will still fail during sampling when required data is missing. Before it was only doing a check during graph construction on some of the input paths. This will make the behavior consistent across different paths.
=> Provide ability to set whether we compute gradients at parameters

src/tdastro/astro_utils/passbands.py, tests/tdastro/astro_utils/test_passband_groups.py
Described in and closes #112:
> When calling `fluxes_to_bandfluxes`, we recalculate the portion of `PassbandGroup.waves` that overlaps with each individual `Passband`'s `waves`. This could be done ahead of time and stored to make `fluxes_to_bandfluxes` faster (and recalculated each time the transmission table is re-gridded).
=> Passband optimization: store wave indices in each Passband

src/tdastro/sources/physical_model.py, tests/tdastro/astro_utils/test_passband_groups.py, tests/tdastro/astro_utils/test_passbands.py
Described in and closes #115:
> We should add a method in source models that:
> - takes in a Passband or PassbandGroup (and time t)
> - evaluates the model based on the Passband/PassbandGroup's `waves` array to get spectral fluxes
> - call the Passband/PassbandGroup's `flux_to_bandflux/fluxes_to_bandfluxes` on these spectral fluxes
> - returns the band fluxes
=> Add get_band_fluxes to source models

src/tdastro/astro_utils/snia_utils.py, tests/tdastro/astro_utils/test_snia_utils.py
Closes #134 
`HostmassX1Func` should return a float (instead of a numpy array with one element) when `num_samples` is 1.
=> Fix the HostmassX1Func return type

src/tdastro/astro_utils/unit_utils.py, tests/tdastro/astro_utils/test_unit_utils.py
Adds `fnu_to_flam`, right now we need it for testing purposes only, closes #146 
It also slightly refactors `flam_to_fnu` for better function signature and replacing wavelength repetition code with broadcasting.
=> Utility function to convert F_ν to F_λ

src/tdastro/sources/galaxy_models.py, src/tdastro/sources/periodic_source.py, src/tdastro/sources/physical_model.py, src/tdastro/sources/sncomso_models.py, src/tdastro/sources/spline_model.py, src/tdastro/sources/static_source.py, src/tdastro/sources/step_source.py
Rename `_evaluate()` to make it distinct from `evaluate()`.
=> Rename _evaluate to compute_flux()

src/tdastro/graph_state.py, src/tdastro/sources/physical_model.py, tests/tdastro/test_graph_state.py
Add some IO and helper functions for `GraphState`:
- Transform a `GraphState` to/from an AstroPy Table.
- Save/Read a `GraphState` to a ecsv file.
- Compare two `GraphState`s for equality.
These will be used in the future to save program state and output the lightcurves.
=> Basic IO Functions for GraphState

src/tdastro/astro_utils/passbands.py
I ran into a problem with `flush` causing an error while writing benchmarks. I need to commit this fix before the new benchmarks.
=> Remove flush that is causing benchmarking errors

src/tdastro/astro_utils/snia_utils.py, tests/tdastro/astro_utils/test_snia_utils.py
Instead of creating a new `FlatLambdaCDM` with each function call, create it once and store it in the object. This allows us to pass a vector of redshifts and get back a vector of dist_mods.
=> Vectorize DistModFromRedshift

src/tdastro/rand_nodes/scipy_random.py, tests/tdastro/rand_nodes/test_scipy_random.py
Closes #166 
Allows the user to give `NumericalInversePolynomialFunc` a PDF function directly instead of wrapping it in a class. Includes an example distribution and calls in the test.
=> Allow NumericalInversePolynomialFunc to take a function

src/tdastro/astro_utils/opsim.py, src/tdastro/example_runs/simulate_snia.py
The user should not need to know about the colmap in `OpSim`. This provides a quick check that will auto-apply the colmap if it is present and has the correct mapping.
=> Helper function for auto-applying colmap

src/tdastro/graph_state.py, tests/tdastro/test_graph_state.py
For common parameters, we might want to extract them from the GraphState without going through the node. This is useful in both logging and debugging. This PR adds a helper function that can extract (uniquely named) parameters from arbitrary nodes in the graph.
=> Add a helper function for looking at variables

src/tdastro/base_models.py, tests/tdastro/sources/test_physical_models.py, tests/tdastro/sources/test_sncosmo_models.py, tests/tdastro/sources/test_static_source.py, tests/tdastro/test_base_models.py
Simplify some of the aspects of the `ParameterizedNode`:
1) Don't precompute and store `direct_dependencies` as it is only used in a single place.
2) Change default node string from "pos:class_name" to "class_name_pos"
3) Simplify `extra_tag` logic that `FunctionNode` was using to include the function name. Instead `FunctionNode` just generates the new name and passes that along.
=> A few small clean ups to node naming and data storage

src/tdastro/example_runs/simulate_snia.py, src/tdastro/sources/sncomso_models.py
Sncosmo models currently fail when `node_label` is given because it tries to parse it as one of the sncosmo parameters.
=> Fix how node_label is passed by sncosmo models.

src/tdastro/astro_utils/unit_utils.py
Do a single matrix multiply instead of carrying the units through the full computation.
=> Speed up unit conversions

src/tdastro/example_runs/simulate_snia.py, src/tdastro/sources/sncomso_models.py, tests/tdastro/sources/test_snia.py
Refactor test_snia.py to break up the code and make it easier to debug/profile. The only behavioral change is making the comparison with a direct sncosmo computation optional. This speeds things up a bit during simulation.
A few stylistic cleanups:
- Adopts the new parameter access methods, so we do not have to go through the node's `get_param` function.
- Samples all runs at the beginning instead of in the core loop. This is more efficient for large number of samples.
=> Refactor test_snia.py

src/tdastro/base_models.py, src/tdastro/sources/physical_model.py, src/tdastro/sources/sncomso_models.py, tests/tdastro/test_base_models.py
The node strings must be unique in order to store the data internally in a `GraphState`. This PR changes the logic to check that each node seen during sampling has a unique string.
Also adds a few very small performance optimizations (e.g. `np.array` -> `np.asarray`).
=> Improve error checking for node labels

src/tdastro/math_nodes/given_sampler.py, tests/tdastro/math_nodes/test_given_sampler.py
Building off the pzflow sampling request (PR #181), add the ability to pre-sample data into an AstroPy table or Pandas DataFrame and then retrieve it during sampling.
This could look like:
```
from pzflow import Flow
my_flow = Flow(file="something.pkl")
sample_table = flow.sample(1000)
flow_results_node = TableSampler(sample_table)
```
=> Add ability to pull information from Pandas DataFrame or AstroPy Table

src/tdastro/math_nodes/basic_math_node.py, tests/tdastro/math_nodes/test_basic_math_node.py
closes #188 
Add logging to record the expression being evaluated and the parameters used when an exception is encountered in a `BasicMathNode`.
=> Add some basic logging for errors in math node

src/tdastro/graph_state.py, tests/tdastro/test_graph_state.py
Adds two new features that were requested in the review of #185
1) Adds a convenience function that allows the user to access a node's variables directly when there is only a single node in the `GraphState` (see #187)
2) Allows iteration over each of the states within a `GraphState` that has multiple samples (see #186)
Closes #187 
Closes #186
=> Add two features requested in the review of PR185

src/tdastro/sources/salt2_jax.py, tests/tdastro/sources/test_salt2.py
Change the default units for the JAX Salt2 model to nJy. Updates the unit test to compare against the wrapped sncosmo SALT2 instead of the raw sncosmo code.
=> Fix the units for the JAX SALT2 model

src/tdastro/astro_utils/passbands.py, tests/tdastro/astro_utils/test_passband_groups.py
Two small changes to the passbands code:
1) Move the `_in_band_wave_indices` from the passbands to the passband group for better encapsulation. The passbands do not need to know anything about the large group they are in.
2) Combine two preprocessing functions that should always be called together.
=> Small restructuring of passbands

src/tdastro/astro_utils/passbands.py, src/tdastro/sources/physical_model.py, tests/tdastro/astro_utils/test_passbands.py, tests/tdastro/sources/test_physical_models.py
Closes #192 
Allow a GraphState with multiple samples to be passed to `PhysicalModel.evaluate()` and `PhysicalModel.get_band_fluxes()`. In the process update `Passband.fluxes_to_bandflux()` so that it can also process a batch of samples at once.
=> Create batch versions of multiple evaluation functions

src/tdastro/base_models.py, src/tdastro/sources/galaxy_models.py, src/tdastro/sources/periodic_source.py, src/tdastro/sources/periodic_variable_star.py, src/tdastro/sources/physical_model.py, src/tdastro/sources/salt2_jax.py, src/tdastro/sources/sncomso_models.py, src/tdastro/sources/snia_host.py, src/tdastro/sources/spline_model.py, src/tdastro/sources/static_source.py, src/tdastro/sources/step_source.py, tests/tdastro/math_nodes/test_single_value_node.py, tests/tdastro/sources/test_physical_models.py, tests/tdastro/test_base_models.py
There is probably a better way to do this using meta-programming and inheriting part of the docstrings. But for now, we just list out the parameterized values that different `PhysicalModel` nodes have. This will help new users know what can be set.
Also add two helper functions:
- `list_params()` is for interactive development and debugging if a user wants to check what parameters are there (any node, not just a Physical Model).
- `has_valid_param()` performs a contains and a is not None check
=> Expand documentation of the inherited parameterized values

src/tdastro/sources/galaxy_models.py, src/tdastro/sources/periodic_source.py, src/tdastro/sources/periodic_variable_star.py, src/tdastro/sources/physical_model.py, src/tdastro/sources/salt2_jax.py, src/tdastro/sources/sncomso_models.py, src/tdastro/sources/snia_host.py, src/tdastro/sources/spline_model.py, src/tdastro/sources/static_source.py, src/tdastro/sources/step_source.py, tests/tdastro/sources/test_physical_models.py, tests/tdastro/sources/test_salt2.py, tests/tdastro/sources/test_sncosmo_models.py, tests/tdastro/sources/test_static_source.py
Originally we decided not to include a `t0` parameter in the `PhysicalModel` class, because it won't be used by all models. However we currently fail if we apply redshift without a valid `t0`. This PR includes `t0` in the base `PhysicalModel` and sets it to 0.0 (no effect) by default.
We also use the occurrence of `t0` to allow filtering by time to match the time pruning done in @mi-dai 's notebook in #205. By default the `PhysicalModel` uses all times. But subclasses, such as sncosmo models, can add their own restrictions.
=> Move t0 into PhysicalModel

src/tdastro/astro_utils/opsim.py, tests/tdastro/astro_utils/test_opsim.py
Allow a default search radius so we can pass all the information needed for spatial matching together in a single `OpSim` object.
=> Provide ability to use a default search radius for the OpSim

src/tdastro/sources/sncomso_models.py, tests/tdastro/sources/test_sncosmo_models.py
Instead of crashing when given wavelengths out of bounds, return zero flux in those wavelengths.
=> Add bounds checking for sncosmo models

.gitignore, src/tdastro/graph_state.py, tests/tdastro/test_graph_state.py
Fix a small bug in `GraphState.to_dict()` where the code would throw an error if there was only one sample and thus the data is not iterable (to create a list).
=> Fix bug in GraphState.to_dict

docs/notebooks/passband-demo.ipynb, src/tdastro/utils/plotting.py
Change `plot_lightcurves()` to handle more realistic data (an array of filters instead of assuming every filter is observed at every time step). Also adds (optional) error bars.
Keep the old functionality of plotting the unsampled lightcurves as `plot_bandflux_lightcurves()`.
=> Add new light curve plotting helper

tests/tdastro/astro_utils/test_passbands.py
One of the tests is failing because it uses random numbers that occasionally result in bad choices. This PR fixes the flaky test by setting a seed for the random number generator.
=> Fix flaky test

src/tdastro/base_models.py, src/tdastro/graph_state.py
Always store the internal `GraphState` data as arrays to enable vectorization of operations.
=> Always store the internal GraphState as arrays.

src/tdastro/astro_utils/snia_utils.py, tests/tdastro/astro_utils/test_snia_utils.py
While writing the tutorial for statistical sampling I ran into a bug where the cosmology code throws an error if given multiple parameters. This PR tests that they are constants.
=> Add a check that the cosmology parameters are constants

benchmarks/benchmarks.py, src/tdastro/effects/effect_model.py, src/tdastro/effects/white_noise.py, src/tdastro/sources/basic_sources.py, src/tdastro/sources/galaxy_models.py, src/tdastro/sources/periodic_source.py, src/tdastro/sources/periodic_variable_star.py, src/tdastro/sources/physical_model.py, src/tdastro/sources/salt2_jax.py, src/tdastro/sources/sncomso_models.py, src/tdastro/sources/snia_host.py, src/tdastro/sources/spline_model.py, tests/tdastro/effects/test_effect_model.py, tests/tdastro/effects/test_white_noise.py, tests/tdastro/sources/test_basic_sources.py
Add the ability to pass a list of effects into the `PhysicalModel`. These effects are automatically broken into "rest frame" effects (which are applied before the results are redshifted back) and "observer frame" effects, which are applied afterward.
The PR also moves the white noise effect back into an `EffectModel` (instead of being hard coded into `PhysicalModel`).
=> Re-add the ability to specify a list of effects

src/tdastro/astro_utils/passbands.py, tests/tdastro/astro_utils/test_passband_groups.py
Break out the function that does the actual computation of the bandpass fluxes for a single filter so we can use without evaluating all the filters in the passband group (mostly for testing right now).
=> Break out a fluxes_to_passband function for a single passband.

src/tdastro/effects/effect_model.py, src/tdastro/effects/white_noise.py, src/tdastro/sources/physical_model.py, tests/tdastro/sources/test_physical_models.py
The current redshift computation is broken for multiple samples because it does not maintain a constant observer frame copy of wavelengths or time. Instead both arrays are redshifted on each iteration. This fixes that problem by creating new `rest_time` and `rest_wave` copies to represent the redshifted values.
It also passes times (optionally) to the `EffectsModels` (which is how I found the problem).
=> Fix the redshift computation with multiple samples

docs/notebooks/addings_effects.ipynb, src/tdastro/astro_utils/dustmap.py, src/tdastro/base_models.py, src/tdastro/sources/physical_model.py, tests/tdastro/astro_utils/test_dustmap.py, tests/tdastro/effects/test_extinction.py, tests/tdastro/effects/test_white_noise.py
Add a wrapper for the dustmap package (without directly depending on that package). Include a test (constant) dustmap and a notebook of how to use effects in general.
The PR also:
- Fixes a small bug that would cause an error when the name of the output of a function node was not "function_node_result".
- Moves the effects from a list passed in the constructor to an `add_effect` function. This allows easier setup for effects that depend on model parameters, such as RA and dec.
=> Add a dust map wrapper

src/tdastro/astro_utils/opsim.py, src/tdastro/math_nodes/ra_dec_sampler.py, tests/tdastro/astro_utils/test_opsim.py, tests/tdastro/math_nodes/test_ra_dec_sampler.py
Add a placeholder sampler to sample uniformly by the region covered by an OpSim. This uses rejection sampling and will be infeasibly slow for OpSims with small coverage. This is primarily a placeholder until we can add an approach that does some pre-computation of the OpSim region (which will be in a later PR).
=> Add a basic sampler to do (RA, dec) sampling from an opsim

docs/notebooks/sampling_positions.ipynb, pyproject.toml, src/tdastro/math_nodes/ra_dec_sampler.py, src/tdastro/opsim/opsim.py, tests/tdastro/math_nodes/test_ra_dec_sampler.py, tests/tdastro/opsim/test_opsim.py
This PR adds the ability for users to generate a healsparse coverage map from an `OpSim` and to sample (RA, dec) points from that coverage map. It also adds a notebook tutorial demonstrating the different approaches for sampling (RA, dec) points.
=> Add the ability to sample from an OpSim's coverage

docs/notebooks/passband-demo.ipynb, src/tdastro/astro_utils/passbands.py, tests/tdastro/astro_utils/test_passband_groups.py, tests/tdastro/astro_utils/test_passbands.py
Adds support for ZTF passbands (and any other sncosmo passbands). Also refactors the code to:
- Create separate code paths for building a `Passband` from a file, a numpy array, or an `sncosmo.Bandpass` object.
- Add support for manually adding a passband.
- Change `_load_preset` to `add_preset` to allow a user to load passbands from multiple surveys.
Also adds some more tests.
=> Add support for ZTF passbands

src/tdastro/example_runs/simulate_snia.py, tests/tdastro/sources/test_snia.py
test_snia is occasionally failing due to randomness in the smoke tests. This uses a fixed seed for test so that we do not get occasional failures.
=> Control randomness in test_snia

src/tdastro/sources/sncomso_models.py, src/tdastro/utils/wave_extrapolate.py, tests/tdastro/sources/test_sncosmo_models.py, tests/tdastro/utils/test_wave_extrapolate.py
Allow custom extrapolation beyond the wavelength bounds for sncosmo models. Since we might want to support this with other model types, we add an wave extrapolation class that can be reused (instead of putting this all in the sncosmo model itself).
=> Provide basic extrapolation functions for sncosmo

src/tdastro/astro_utils/passbands.py, tests/tdastro/astro_utils/test_passbands.py
Closes #113 
This is the last outstanding item of #113.  The `Passband` class already converts everything to Angstroms. This PR just removes the "units" attribute and updates the docstrings.
=> Make Passband always use Angstroms

.copier-answers.yml, .github/workflows/asv-main.yml, .github/workflows/asv-nightly.yml, .github/workflows/asv-pr.yml, .github/workflows/build-documentation.yml, .github/workflows/pre-commit-ci.yml, .github/workflows/publish-to-pypi.yml, .github/workflows/smoke-test.yml, .github/workflows/testing-and-coverage.yml, .readthedocs.yml, benchmarks/asv.conf.json, docs/index.rst, pyproject.toml, src/tdastro/opsim/opsim.py, tests/tdastro/astro_utils/test_passbands.py
Upgrade TDAstro to use numpy>2.0. This requires using >= 0.4.7 of the extinction package.
Also:
- changes `trapz` to `trapezoid` since `trapz` was recently deprecated in numpy.
- changes the test matrix to drop Python 3.9 and use Python 3.12
=> Upgrade to numpy 2.0

src/tdastro/sources/basic_sources.py, src/tdastro/sources/physical_model.py, src/tdastro/sources/sncomso_models.py, src/tdastro/sources/spline_model.py, src/tdastro/utils/wave_extrapolate.py, tests/tdastro/sources/test_basic_sources.py, tests/tdastro/sources/test_spline_source.py
Other models beyond `SncosmoWrapperModel` may need extrapolation, such as `SplineModel`.  This PR enables extrapolation for **all** models with provided wavelength bounds, by moving the computation into `PhysicalModel`.
=> Make extrapolation available to all models

docs/notebooks/sampling.ipynb, docs/notebooks/technical_overview.ipynb, src/tdastro/effects/basic_effects.py, src/tdastro/sources/multi_source_model.py, src/tdastro/sources/physical_model.py, tests/tdastro/effects/test_basic_effects.py, tests/tdastro/sources/test_galaxy_models.py, tests/tdastro/sources/test_multi_source_models.py
Closes #281 
Add a `MultiSourceModel` that computes the flux as the (weighted) sum from a list of individual sources. Remove `PhysicalModel`'s background attribute in favor of this (**warning: this will be a breaking change**). This provides more flexibility and also consistency in how the effects are applied.
For testing purposes we add a toy effect `ConstantDimming`.
=> Replace PhysicalModel's background with MultiSourceModel

src/tdastro/sources/lightcurve_source.py, tests/tdastro/sources/test_lightcurve_source.py
Expand the `LightCurveSource` model to support periodic curves (with some restrictions) and to use a default "baseline" value outside the time range of the curves.
=> Expand LightcurveSource

src/tdastro/sources/lightcurve_source.py, tests/tdastro/sources/test_lightcurve_source.py
Break out the lightcurve-based data from `LightcurveSource`. This is an initial step before allowing a source to have a list of lightcurves, in which case this will be a list of `LightcurveData`.
Most of this PR is moving functionality from `LightcurveSource` to `LightcurveData`.  It also adds a helper function to read `LightcurveData` from an LCLIB style table.
=> Break lightcurve data into its own object

src/tdastro/astro_utils/passbands.py, tests/tdastro/astro_utils/test_passband_groups.py
The LSST data files are provided in nm.  This was not always manually specified in the notebooks.  So add a check and specify it if not units provided.
=> Fix units for LSST preset

src/tdastro/sources/lightcurve_source.py, tests/tdastro/sources/test_lightcurve_source.py
Capturing some of Mi's comments from PR312 of renaming internal variables for clarity. I held off on a few other renaming, because that would need changes in other files.
I also blocked adding effects to the LightcurveSource models as we discuss.
=> Small fixes to variable renaming

src/tdastro/sources/lightcurve_source.py, tests/tdastro/sources/test_lightcurve_source.py
Closes #330 
Save the template values (fluxes, not magnitudes) for a randomly selected light curve in the `MultiLightcurveSource` model. We do this by using a `GivenValueSelector` node to map the index parameter (`selected_lightcurve`) to the corresponding value in a list of template values for each light curve. Since parameters are always sampled in the order in which they are added, we will sample the index first and then can lookup the corresponding template values.
=> Save the baseline/template values for the randomly selected lightcurves

src/tdastro/math_nodes/given_sampler.py, src/tdastro/math_nodes/np_random.py, tests/tdastro/math_nodes/test_given_sampler.py, tests/tdastro/math_nodes/test_np_random.py
The choice function does not work as expected for the `NumpyRandomFunc` node. We raise an error to indicate that it is not a supported function and point the user to the `GivenValueSampler` node instead. This PR also extends the `GivenValueSampler` node to take an integer N to return a choice of [0, N-1)
=> Provide alternate for NP's choice function

docs/index.rst, docs/notebooks.rst
Expand the instructions for getting started with TDAstro to include: how to set up a virtual environment and link the kernel in jupyter. These instructions are sufficient for people to use TDAstro on the RSP.
=> Expand Getting Started

docs/notebooks/adding_sources.ipynb
Add a note to the documentation that new models do not need to implement redshift conversions themselves. This is already handled by the parent class.
=> Small documentation updates

src/tdastro/sources/salt2_jax.py, tests/tdastro/sources/test_salt2.py
The `SALT2JaxModel` was failing when redshift != 0.0 because the `t0` parameter was not being passed along to the `PhysicalModel` constructor. By including `t0=0.0` in the argument list, that parameter was not included in `**kwargs` and hence not passed along. This PR fixes that and adds a corresponding test.
=> Fix broken Salt2JAX model

src/tdastro/sources/salt2_jax.py, tests/tdastro/sources/test_salt2.py
`SALT2JaxModel`'s `compute_flux()` was taking phase instead of times and was giving wrong values. updated to calculate phase from times, and updated tests to use non-zero t0. (Old tests did not fail because t0=0 so phase=times)
=> modified salt2jax model 

docs/notebooks/introduction.ipynb, src/tdastro/graph_state.py, tests/tdastro/test_graph_state.py, tests/tdastro/test_simulate.py
Closes #371 
Add helpers to recreate a `GraphState` object from the dictionaries that we store in the output table.
=> Add helpers for recreating a GraphState

src/tdastro/sources/lightcurve_source.py, src/tdastro/sources/multi_source_model.py, src/tdastro/sources/physical_model.py
We removed background models a while back (and instead use `AdditiveMultiSourceModel`). But we left in some of the (now unneeded) checks that background model is not set. This cleans those up.
=> Remove references to background model

src/tdastro/sources/static_sed_source.py, tests/tdastro/sources/test_static_sed_source.py
Create a version of the `StaticSEDSource` that works at the bandflux level. This could be done using the current `LightcurveSource`, but this implementation is more efficient. The main motivation is two fold: 1) creating constant "stars" where we just have bandflux level data and 2) add another helper for testing.
=> Add a constant bandflux model

benchmarks/benchmarks.py
Fix the broken test, which is failing because we removed `evaluate_sed()` from Bandflux models.
=> Fix broken benchmark

docs/notebooks/opsim_notebook.ipynb, pyproject.toml, src/tdastro/math_nodes/ra_dec_sampler.py, src/tdastro/obstable/obs_table.py, tests/tdastro/math_nodes/test_ra_dec_sampler.py, tests/tdastro/obstable/test_obs_table.py
Closes #416 
Instead of sampling from an survey's coverage using rejection sampling, provide an approach that creates a `MOC` from the `ObsTable` and then samples the `MOC`. This has the additional benefit that we can create MOCs that are the union or intersection of survey footprints.
=> Create a more efficient mechanism for sampling from an ObsTable's coverage

src/tdastro/math_nodes/ra_dec_sampler.py, tests/tdastro/math_nodes/test_ra_dec_sampler.py
The data stored in `ApproximateMOCSampler` is a list of healpix IDs at a given depth instead of an actual MOC. This PR fixes the name.
=> Fix name of healpix list

src/tdastro/astro_utils/passbands.py
Fix the warning that:
```
tests/tdastro/astro_utils/test_passband_groups.py::test_passband_group_roman_preset
/Users/jkubica/h/tdastro/src/tdastro/astro_utils/passbands.py:360: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
table = pd.read_csv(table_path, comment="#", sep=r"[\s,]+")
```
by adding the `engine='python'` argument.
=> Fix test warning

src/tdastro/base_models.py, src/tdastro/graph_state.py, tests/tdastro/math_nodes/test_np_random.py, tests/tdastro/test_base_models.py, tests/tdastro/test_graph_state.py
Adds the ability to create a DAG of parameters for testing, analysis, visualization, and documentation. This is the first step of automatically building the DAG from the graph of `ParameterizedNode`. Ultimately we want to use this to provide tools (such as a dependency visualizer) that helps the user understand the current model.
=> Add a helper function to create a DAG of parameters

src/lightcurvelynx/utils/plotting.py
Have each of the plotting functions return the axis for the plot so we can do future annotations (see PR #466 for an example).
=> Plotting functions return the axis

src/lightcurvelynx/math_nodes/ra_dec_sampler.py, src/lightcurvelynx/obstable/obs_table.py, tests/lightcurvelynx/math_nodes/test_ra_dec_sampler.py, tests/lightcurvelynx/obstable/test_obs_table.py
There were a few bugs found when debugging @mi-dai 's notebook that this PR fixes:
1) We should use the OpsTable's radius for RA, dec sampling unless a specific alternative is provided.
2) The `radius` attribute had been moved to a dictionary entry so the assignment `ztf_obstable.radius` was not being used in the actual simulation. This PR adds a property that allows user to access and set ObsTable radius with `.radius`
=> Fix problems with RA, dec sampling

tests/lightcurvelynx/astro_utils/test_mag_flux.py
Use a fixed random seed to prevent test flakiness. The tests fail very rarely due to small numerical precision issues (relative error just above 10e-10).
=> Fix flaky tests

src/lightcurvelynx/math_nodes/ra_dec_sampler.py, tests/lightcurvelynx/math_nodes/test_ra_dec_sampler.py
Improve the efficiency of the `ObsTableUniformRADECSampler` by only testing the newly generated points (instead of checking everything, including the previously valid points). This does not fix the problems we occasionally see with the samples being out of bounds. But it makes debugging more efficient.
Also increase the coverage of the tests.
=> Improve efficiency of ObsTableUniformRADECSampler

src/lightcurvelynx/astro_utils/passbands.py, src/lightcurvelynx/example_runs/simulate_snia.py, src/lightcurvelynx/models/lightcurve_template_model.py, tests/lightcurvelynx/astro_utils/test_passband_groups.py, tests/lightcurvelynx/astro_utils/test_passbands.py
Rename the tables in the `Passband` class to be more accurate:
- `processed_transmission_table` -> `normalized_system_response`
- `_loaded_table` -> `transmission_table`
=> Rename the tables in the Passbands
