src/tdastro/base_models.py, src/tdastro/sources/static_source.py, tests/tdastro/effects/test_white_noise.py, tests/tdastro/sources/test_static_source.py
Return a T x N matrix of SED observations from each source where T is the number of time stamps and N is the number of wavelengths we are sampling.
=> The sources produce SEDs instead of point observations

src/tdastro/base_models.py
=> Fix duplicate parameter error message

src/tdastro/base_models.py, tests/tdastro/sources/test_static_source.py, tests/tdastro/test_base_models.py
Allow the users to change the settings of parameters within a `PhysicalModel`.
=> Allow users to change parameter settings

src/tdastro/base_models.py, src/tdastro/populations/fixed_population.py, tests/tdastro/populations/test_fixed_population.py
Create a class to store and sample from populations of `PhysicalModel`s.
=> Create a population level model

src/tdastro/base_models.py, src/tdastro/sources/galaxy_models.py, tests/tdastro/sources/test_galaxy_models.py
Creates the concept of a background to a `PhysicalModel` which is just another `PhysicalModel` that adds flux. Illustrate this was a spherical galaxy whose brightness is a Gaussian function of distance from the center. The source is sampled based on the galaxy's parameters and the contributed flux depends on the relative position of the source and galaxy center.
=> Create the ability to sample from a background model

src/tdastro/base_models.py, src/tdastro/effects/effect_model.py, src/tdastro/effects/white_noise.py, src/tdastro/populations/fixed_population.py, src/tdastro/populations/population_model.py, src/tdastro/sources/galaxy_models.py, src/tdastro/sources/physical_model.py, src/tdastro/sources/sncomso_models.py, src/tdastro/sources/spline_model.py, src/tdastro/sources/static_source.py, src/tdastro/sources/step_source.py, tests/tdastro/sources/test_sncosmo_models.py, tests/tdastro/sources/test_spline_source.py, tests/tdastro/sources/test_static_source.py, tests/tdastro/sources/test_step_source.py, tests/tdastro/test_base_models.py
Three main changes:
1) All the `__str__()` functions are now handled in the base class (`ParameterizedNode`) so that each subclass does not need to repeat them.
2) `ParameterizedNode`s can now have identifiers so we can tell two nodes of the same class apart.
3) Add a helper function to extract all of the attribute settings in the DAG.
=> Improve debugging of TDAstro DAG

src/tdastro/base_models.py, src/tdastro/sources/periodic_variable_star.py, tests/tdastro/test_base_models.py
=> Add ability to overwrite existing attributes

src/tdastro/astro_utils/cosmology.py, src/tdastro/base_models.py, src/tdastro/effects/redshift.py, tests/tdastro/sources/test_sncosmo_models.py, tests/tdastro/sources/test_spline_source.py, tests/tdastro/sources/test_static_source.py, tests/tdastro/test_base_models.py
Add the ability to specify a to set a random seed for all the nodes in a graph. The nodes will each have a specialized seed that is a function of the graph's base seed and their name.
We need to add validity functions to check that all names in a graph are unique.
=> Add the ability to set a graph-wide random seed.

tests/tdastro/astro_utils/test_cosmology.py, tests/tdastro/sources/test_physical_models.py
Add a few additional tests to check that the redshift function node results match at different points.
=> Add tests for cosmology

src/tdastro/base_models.py, src/tdastro/sources/periodic_variable_star.py, tests/tdastro/test_base_models.py
Various cleanups from our in person discussion, including adding comments and removing unneeded variables.
=> Various cleanups

src/tdastro/base_models.py, src/tdastro/sources/physical_model.py, tests/tdastro/sources/test_physical_models.py, tests/tdastro/test_base_models.py
Create a simple recursive function to assemble various node information such as: all the node labels, all the node strings, or all the node hash values.
=> Add basic getter for node information

src/tdastro/astro_utils/opsim.py, tests/tdastro/astro_utils/test_opsim.py
Wrap the opsim functions in a class OpSim and prebuild an internal kd-tree to do fast lookups of of whether a point is included within the survey. Most of the actual code is unchanged, but shows up as a change because it is now part of a class.
=> Optimize the OpSim Search

.copier-answers.yml, .github/workflows/asv-main.yml, .github/workflows/asv-nightly.yml, .github/workflows/asv-pr.yml, .github/workflows/publish-benchmarks-pr.yml, .pre-commit-config.yaml, benchmarks/asv.conf.json, benchmarks/benchmarks.py, pyproject.toml
Uses the Python Project Template to turn on benchmarking for TDAstro and adds a single benchmark.
=> Enable basic benchmarks for TDAstro

src/tdastro/astro_utils/opsim.py, tests/tdastro/astro_utils/test_opsim.py, tests/tdastro/sources/test_snia.py
Add a `get_observations()` function that does the range search and returns specific columns of the matching observations. This can replace the `get_observed_times()` function.
=> Add a get_observations function

tests/tdastro/sources/test_snia.py
Test was failing because the wrong key was used.
=> Fix broken test

tests/tdastro/astro_utils/test_passbands.py
=> Remove failing GAIA test

src/tdastro/astro_utils/snia_utils.py, src/tdastro/graph_state.py, src/tdastro/util_nodes/scipy_random.py, tests/tdastro/astro_utils/test_snia_utils.py, tests/tdastro/test_graph_state.py, tests/tdastro/util_nodes/test_scipy_random.py
Create a new `NumericalInversePolynomialFunc` node that wraps scipy's `NumericalInversePolynomial`. This wrapping allows us to reuse all the of the infrastructure for getting and setting seeds.
Change `HostmassX1Func` to use this `NumericalInversePolynomialFunc`. Add a bunch of tests to confirm that it is generating both new samples and underlying hostmasses.
=> Adapt HostmassX1Func to use random node infrastructure

src/tdastro/astro_utils/snia_utils.py
Optimize sampling of X1 from hostmass by creating two inverse distributions (one for hostmass >= 10.0 and one for hostmass < 10.0). Batch sample from the two of these instead of creating a new inverse distribution for every single sample.
=> Optimize X1 from Hostmass Sampling

pyproject.toml
=> ignore linting code N806 to allow non-lowercase variables (such as H0)

src/tdastro/sources/physical_model.py, tests/tdastro/sources/test_physical_models.py
Allow the user to sample the data without applying redshift (even when redshift is specified).
=> Add a flag to turn off redshift application

.copier-answers.yml, .github/workflows/asv-main.yml, .github/workflows/asv-nightly.yml, .github/workflows/asv-pr.yml, .pre-commit-config.yaml, LICENSE
Reapply the python project template (`copier update --vcs-ref=HEAD`) to update the ASV scripts.
=> Update ASV scripts

src/tdastro/base_models.py, tests/tdastro/test_base_models.py
This doesn't add any new functionality, but provides an easier path for getting parameter values.
=> Add syntactic shortcut for accessing parameters

benchmarks/benchmarks.py
Add a lot more benchmarks based on the snia_test notebook.
=> Expand the benchmark suite

docs/notebooks/test_snia.ipynb, src/tdastro/astro_utils/passbands.py, src/tdastro/graph_state.py, tests/tdastro/astro_utils/test_opsim.py, tests/tdastro/astro_utils/test_passbands.py, tests/tdastro/conftest.py, tests/tdastro/test_graph_state.py
Replace all instances of f-format paths and os.join paths with `Path()`
=> Replace os.join with Path

docs/notebooks/passband-demo.ipynb, src/tdastro/astro_utils/passbands.py, src/tdastro/utils/plotting.py, tests/tdastro/astro_utils/test_passband_groups.py
Break the plotting functions out from the passbands demo notebook so that we can use them in other notebooks or for analysis. This also fixes a bug in the notebook where the wavelength range of the spline model did not overlap the wavelength range of the passbands.
=> Break out plotting functions

pyproject.toml, src/tdastro/simulate.py, tests/tdastro/test_simulate.py
Adds a module that performs the core steps of simulation and stores the data in a nested-pandas DataFrame.
=> Add a core simulation module

src/tdastro/base_models.py, src/tdastro/graph_state.py, tests/tdastro/sources/test_basic_sources.py, tests/tdastro/test_base_models.py, tests/tdastro/test_graph_state.py
Add better error strings for the core functions to help new users better understand failures and how to debug them.
=> Add better error strings (and some more tests).

docs/notebooks/adding_sources.ipynb
This PR creates an initial demo notebook for creating new sources.
=> Add a notebook demoing how to create new types of sources.

src/tdastro/astro_utils/opsim.py, tests/tdastro/astro_utils/test_opsim.py
=> Address issue 234

src/tdastro/astro_utils/pzflow_node.py, src/tdastro/base_models.py, src/tdastro/math_nodes/distribution_sampler.py, src/tdastro/math_nodes/given_sampler.py, tests/tdastro/math_nodes/test_distribution_sampler.py
Add FunctionNode the performs a similar functionality to SNANA's `DistributionSampler`, but uses different interpolation to avoid values ever going below 0.0. This version may be less accurate in some cases.
=> Add the ability to sample from an empirically defined distribution.

tests/tdastro/astro_utils/test_opsim.py, tests/tdastro/astro_utils/test_passband_groups.py, tests/tdastro/astro_utils/test_passbands.py, tests/tdastro/astro_utils/test_unit_utils.py
Add some error condition tests to TDAstro to cover more of the edge cases.
=> Expand code coverage

docs/notebooks.rst, docs/notebooks/sampling.ipynb, src/tdastro/math_nodes/basic_math_node.py, tests/tdastro/math_nodes/test_basic_math_node.py
Provides more details on how sampling works and how nodes can be linked. There is some overlap with the introduction notebook, but this will be cleaned up in a future PR.
=> Create a new introductory notebook for parameter sampling

pyproject.toml, src/tdastro/effects/extinction.py, tests/tdastro/effects/test_extinction.py
Create an effect the applies a dust extinction given an ebv. This will later be chained with an effect that computes the ebv from the dustmap. So effectively this performs part of what #180 is meant to do. But by breaking this into two stages, we can be a lot more flexible.
=> Add an extinction effect

src/tdastro/opsim/ztf_opsim.py, tests/tdastro/opsim/test_ztf_opsim.py
Update ZTF Opsim to make it consistent in units
=> update ztf opsim and test after rebase

src/tdastro/opsim/opsim.py, src/tdastro/opsim/ztf_opsim.py, tests/tdastro/opsim/test_opsim.py, tests/tdastro/opsim/test_ztf_opsim.py
Move some of the settings to internal class variables to make subclassing a bit cleaner.
=> Opsim cleanup

src/tdastro/astro_utils/dustmap.py
I forgot to update the comment after adding the automatic downloading
=> Fix comment in dustmap.py

src/tdastro/opsim/ztf_opsim.py
Fix two bugs (See description in commits). I think we need a test for `ZTFOpsim.from_db`?
=> Ztf opsim bug

tests/tdastro/opsim/test_opsim.py
=> Fix the failing test

README.md
=> Add Introduction to readme

src/tdastro/sources/physical_model.py
=> Make sure filters is a numpy array

src/tdastro/sources/basic_sources.py, tests/tdastro/sources/test_basic_sources.py
=> Add basic redshift test

src/tdastro/sources/spline_model.py, src/tdastro/utils/io_utils.py, tests/tdastro/sources/test_spline_source.py
closes #280 
Adds a `from_file()` constructor to the `SplineModel` class.
=> Add ability to create a SplineModel directly from a file

benchmarks/benchmarks.py
Add some simple benchmarks to capture any changes to performance as a result of changes to base model classes.
=> Add some more simple benchmarks

src/tdastro/sources/lightcurve_source.py
I merged the PR before committing the comment change you requested.
=> Address PR comment

docs/notebooks/adding_sources.ipynb, docs/notebooks/addings_effects.ipynb, docs/notebooks/introduction.ipynb, src/tdastro/base_models.py, src/tdastro/graph_state.py
Add more comments and documentation capturing the thought process behind how the foundation code works (with the goal of having the software be longterm maintainable).
=> Add more comments and documentation

src/tdastro/math_nodes/given_sampler.py, tests/tdastro/math_nodes/test_given_sampler.py
Expand the interface of `GivenValueSampler` to take a vector of weights and sample from that distribution.
=> Allow the GivenValueSampler to take weights

docs/notebooks/pre_executed/plasticc_snia.ipynb
Add a note about downloading the OpSim data to the plasticc_snia notebook.
=> Add a note on downloading the OpSim data

src/tdastro/astro_utils/passbands.py, tests/tdastro/astro_utils/test_passband_groups.py
Add a helper accessor for the passband group's filters.
=> Add a helper accessor

src/tdastro/math_nodes/given_sampler.py, tests/tdastro/math_nodes/test_given_sampler.py
Create a node which takes an index as its parameter and returns the corresponding value from a list. This node will be needed to address issue #330 by storing the templated parameters as lists.
=> Add a function node to select a given value from a list

docs/notebooks.rst, docs/notebooks/advanced_sampling.ipynb
Documents some of the approached used to create recent models.
=> Create a notebook of more complex sampling examples

docs/citations.rst, docs/index.rst, docs/notebooks.rst, docs/notebooks/citations.ipynb, src/tdastro/simulate.py
Add documentation on how to generate citations with TDAstro.
=> Add documentation on citations

src/tdastro/sources/agn.py
Closes #351 
Sample's the AGN's inclination uniformly from (0, pi/2)
=> Fix issue 351

src/tdastro/simulate.py, tests/tdastro/test_simulate.py
=> Fix issue 354

src/tdastro/opsim/opsim.py, tests/tdastro/opsim/test_opsim.py
Closes #368
Allow a user to only extract points that are within interest of a time window.
=> Add ability to restrict OpSim search by time range

docs/notebooks/passband-demo.ipynb, src/tdastro/astro_utils/passbands.py
Expand the passband notebook to include information about downloading from SVO.
=> Reorganize and expand Passband notebook

docs/notebooks/host_source_models.ipynb, docs/notebooks/introduction.ipynb, docs/notebooks/microlensing.ipynb, docs/notebooks/technical_overview.ipynb, src/tdastro/sources/basic_sources.py, tests/tdastro/sources/test_basic_sources.py
A pure sine wave is negative half the time, which does not make for realistic plots in notebooks. This PR adds the ability to use an offset and make better plots in the notebooks.
=> Extend the SinWaveSource to be baseline + sinwave

docs/notebooks.rst, docs/notebooks/adding_effects.ipynb, docs/notebooks/time_varying_effects.ipynb, tests/tdastro/effects/test_basic_effects.py
Adding a new example of something you can do with effects that is not covered by current notebooks or examples.
=> Add an example notebook with time varying effects

src/tdastro/math_nodes/ra_dec_sampler.py, tests/tdastro/math_nodes/test_ra_dec_sampler.py
Add the ability to create an `ApproximateMOCSampler` from a saved MOC. This allows users to compute the MOC once, cache it, and load it in for future simulations.
=> Add ability to read in MOC from file

docs/notebooks/sampling_positions.ipynb
Include more information on rejection sampling and MOC sampling
=> Expand the Position Sampling Notebook

src/tdastro/models/lightcurve_template_model.py, tests/tdastro/models/test_lightcurve_template_model.py
Closes #453 
Convert the template mags to fluxes. We are already doing that for the non-baseline values.
=> Fix Issue 453

src/lightcurvelynx/simulate.py, tests/lightcurvelynx/test_simulate.py
Closes #478 by returning more information on the parameters that can be saved.
=> Fix Issue 478

src/lightcurvelynx/astro_utils/snia_utils.py, tests/lightcurvelynx/astro_utils/test_snia_utils.py
Return SN coordinates given host-sn physical separation.
=> calculate sn coordinates given physical separation

src/lightcurvelynx/utils/post_process_results.py, tests/lightcurvelynx/utils/test_post_process_results.py
Add a helper function to concatenate results NestedFrame, translating the ids to make them unique.
=> Add a helper to concatenate results
